topoteretes/cognee

- cognee/infrastructure/databases/graph/config.py
- cognee/modules/cognify/graph/add_cognitive_layer_graphs.py
The cognitive layer graphs can now be correctly added. 
The key change is the following line: 
`graph_model: object = KnowledgeGraph` from the` graph/config`
Given that the graph model was set to `DefaultGraphModel` there was a mismatch of pydantic models in this code block: 
```
if not isinstance(layer_graph, graph_model):
layer_graph = graph_model.parse_obj(layer_graph)
```
from the `cognee/modules/cognify/graph/add_cognitive_layer_graphs.py`
> add_cl_graphs() fixed - config change - graph model -> KnowledgeGraph

- .github/workflows/test_cognee_llama_index_notebook.yml
- .github/workflows/test_cognee_multimedia_notebook.yml
- .github/workflows/test_dynamic_steps_example.yml
- .github/workflows/test_milvus.yml
- .github/workflows/test_multimedia_example.yaml
- .github/workflows/test_neo4j.yml
- .github/workflows/test_notebook.yml
- .github/workflows/test_pgvector.yml
- .github/workflows/test_python_3_10.yml
- .github/workflows/test_python_3_11.yml
- .github/workflows/test_python_3_9.yml
- .github/workflows/test_qdrant.yml
- .github/workflows/test_simple_example.yml
- .github/workflows/test_weaviate.yml
Allow github actions to run on PRs that aren't targeting main
Test
> test: Update gh actions so they can run outside of PR to main

- cognee/infrastructure/files/utils/get_file_metadata.py
- cognee/modules/ingestion/classify.py
fix int unable find method .split, not sure why its a int
> fix int does not have .split function

- cognee/eval_framework/corpus_builder/task_getters/get_default_tasks_by_indices.py
- examples/python/pokemon_datapoints_example.py
- Fixed get_no_summary_tasks and get_just_chunks_tasks to work with the new tasks and pipelines
- Chore: fixed the pokemon example to work with the new tasks and pipelines
> fix: get default tasks

- .github/workflows/test_gemini.yml
> Fix gemini gh action

- .env.template
LiteLLM adds the debugging lines: LiteLLM:INFO to the output when running and can flood the output making actual cognee debugging difficult. This .env config will suppress logging to ERROR level only.
Note there is an open bug with LiteLLM  here [https://github.com/BerriAI/litellm/issues/9815](https://github.com/BerriAI/litellm/issues/9815) as  'cost calculation' lines will still be shown despite ERROR level logging
> Set LiteLLM logging level

- .env.template
- README.md
Document that Cognee collects usage data in the readme and add instructions how users can opt out.
> Document collection of usage data and how to opt out

- .github/workflows/dockerhub-mcp.yml
- Dockerfile
- alembic/versions/482cd6517ce4_add_default_user.py
- alembic/versions/8057ae7329c2_initial_migration.py
- cognee-mcp/Dockerfile
- cognee-mcp/README.md
- cognee-mcp/entrypoint.sh
- cognee-mcp/src/server.py
- docker-compose.yml
Resolve issue with .venv being broken when using docker compose with Cognee
---------
> fix: run cognee in Docker [COG-1961] (#775)

- cognee/infrastructure/databases/graph/networkx/adapter.py
Switch typing from str to UUID for NetworkX node_id
> fix: networkx id type change [COG-1876]

- cognee-mcp/pyproject.toml
- cognee-mcp/src/server.py
> fix: Mcp small updates

- cognee-mcp/pyproject.toml
- cognee-mcp/src/server.py
> feat: Add developer rules

- Dockerfile_modal
- cognee/eval_framework/eval_config.py
- cognee/eval_framework/metrics_dashboard.py
- cognee/eval_framework/modal_run_eval.py
Adds modal parallel evaluation for retriever development
> feat: Adds modal parallel evaluation for retriever development

- cognee/__init__.py
- cognee/shared/logging_utils.py
- cognee/version.py
> feat: added util logger OS 

- cognee/modules/graph/utils/expand_with_nodes_and_edges.py
Removes ontology resolver initialization at import.
> Fix: removes ontology resolver initialization at import 

- cognee/shared/data_models.py
Removes unused properies from node and edge pydantic models.
> feat: removes unused properies from node and edge pydantic models

- Dockerfile
- alembic/versions/482cd6517ce4_add_default_user.py
- cognee-mcp/Dockerfile
- cognee-mcp/entrypoint.sh
- cognee-mcp/uv.lock
- cognee/infrastructure/databases/graph/__init__.py
- cognee/infrastructure/databases/graph/get_graph_engine.py
- cognee/infrastructure/databases/graph/supported_databases.py
- cognee/infrastructure/databases/graph/use_graph_adapter.py
- cognee/infrastructure/databases/vector/__init__.py
- cognee/infrastructure/databases/vector/create_vector_engine.py
- cognee/infrastructure/databases/vector/supported_databases.py
- cognee/infrastructure/databases/vector/use_vector_adapter.py
- docker-compose.yml
- entrypoint.sh
> 0.1.41 Release fixes

- alembic/versions/482cd6517ce4_add_default_user.py
- cognee-frontend/src/modules/ingestion/DatasetsView/DatasetsView.tsx
- cognee-frontend/src/ui/Partials/SearchView/SearchView.tsx
- cognee-frontend/tsconfig.json
- cognee/api/v1/search/routers/get_search_router.py
- entrypoint.sh
Resolve user already exist issue for UI
> Fix default user

- cognee-mcp/README.md
> chore: update mcp readme

- README.md
> chore: add sponsor to readme

- README.md
> chore: announce SaaS launch on readme

- cognee-frontend/.env.template
- cognee-frontend/src/app/(graph)/CrewAITrigger.tsx
- cognee-frontend/src/utils/fetch.ts
This pull request refactors the frontend application to remove hardcoded backend API and WebSocket URLs. The Environment variables are stored at .env.template file which is created in PR. By this you can temporary solve the problem of binding to the same port 8000. You have to bind Cognee Api Server to different Port and then instead of changing the hardcoded urls you only need to change the Port Number in base url which is present in .env . Please let me know if you want to change Port Number of Cognee Api Server from 8000 to different Port Number which will resolve this issue permanently.
> Frontend hardcodes API base URL #1084

- .github/workflows/community_greetings.yml
Fix “Resource not accessible by integration” error in greetings workflow
This PR updates the community | Greetings GitHub Actions workflow to ensure it can successfully post greeting comments on newly opened issues and pull requests — including PRs from forks — without hitting the “Resource not accessible by integration” error.
- Switched PR trigger from `pull_request` to `pull_request_target` to run in the context of the base repository and grant write-scoped `GITHUB_TOKEN` for commenting on forked PRs.  
- Added explicit `permissions` block with:
- `issues: write`  
- `pull-requests: write`  
- Limited triggers to `types: [opened]` for both issues and PRs to avoid unnecessary runs.  
- Preserved existing greeting messages for issues and pull requests.
The workflow was failing because …
> Chore: fix Commutity Greetings workflow permissions

- cognee/infrastructure/databases/graph/kuzu/kuzu_migrate.py
Fixed `ValueError` that was not being properly raised when `version_code` could not be mapped to proper Kuzu version.
> fix: raise error on version mapping failure

- cognee-mcp/src/test_client.py
Potential fix for [https://github.com/topoteretes/cognee/security/code-scanning/147](https://github.com/topoteretes/cognee/security/code-scanning/147)
To fix the problem, we should avoid logging any part of the API key. Instead, we can log a generic message indicating that an API key is configured, without revealing any part of the key. This maintains the functionality of confirming that the key is present, while eliminating the risk of exposing sensitive information. The change should be made in `cognee-mcp/src/test_client.py`, specifically on line 60, replacing the log statement with a safer alternative. No new imports or methods are required.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 147: Clear-text logging of sensitive information

- cognee/infrastructure/databases/graph/kuzu/adapter.py
kuzu + s3 is failing on dev. What's happening is:
1. During cognee.add, run_pipeline uses [`run_tasks`](https://github.com/topoteretes/cognee/blob/dev/cognee/modules/pipelines/operations/pipeline.py#L193-L195)
2. run_tasks calls [`push_to_s3`](https://github.com/topoteretes/cognee/blob/dev/cognee/modules/pipelines/operations/run_tasks.py#L336-L338), which attempts to [checkpoint](https://github.com/topoteretes/cognee/blob/dev/cognee/infrastructure/databases/graph/kuzu/adapter.py#L142) before the push (Kuzu connection is initialized in `cognify`)
Trace:
```
AttributeError: 'NoneType' object has no attribute 'execute'
Traceback (most recent call last):
File "/Users/daulet/PycharmProjects/cognee-source/examples/python/dynamic_steps_example.py", line 219, in <module> …
```
> fix: ensure connection check before executing checkpoint in KuzuAdapter

- cognee/infrastructure/files/storage/StorageManager.py
When using S3 File Storage, sync is failing as S3FileStorage is mistakenly treated as sync context manager:
```
2025-09-01T16:08:33.574379 [error    ] Error uploading file car_and_tech_companies: '_AsyncGeneratorContextManager' object does not support the context manager protocol [cognee.shared.logging_utils] exception_message="'_AsyncGeneratorContextManager' object does not support the context manager protocol" traceback=True
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/daulet/Desktop/dev/cognee-claude/cognee/api/v1/sync/sync.py:414 in _upload_missing_files  │
│                                                                                                  │
│   411 │   │   │   │   file_name = …
```
> fix: remove redundant S3 file path check in StorageManager

- cognee/tasks/temporal_graph/models.py
This PR adds default values and descriptions to the Timestamp pydantic object used in temporal graph.
Adds default value and description to Timestamp pydantic object
Tested it manually, althought I was unable to reproduce the issue (therefore is probably a rare event), but based on the ci/cd logs I fixed the cause.
None
None
None
> Fix: Fixes temporal graph ci/cd

- cognee/api/v1/ui/ui.py
`cognee-cli -ui` has accidentally added - when opening frontend subprocess - an output decoding into text.
On the surface - frontend ui will be stuck loading.
Frontend process hangs as it's output is not being processed (we're expecting bytes).
This change removes the `text=True` added to frontend subprocess
> fix: frontend process output streaming stuck due to incorrect output
