cognee/infrastructure/databases/vector/milvus/MilvusAdapter.py
Resolve issue with embedding data points for Milvus
fix
=> fix: Resolve issue with embedding data points for Milvus

cognee/modules/graph/utils/retrieve_existing_edges.py
Resolve issue regarding UUID being concatinated instead of string
Fix
=> fix: Resolve issue with UUID being concatinated instead of string

cognee/api/v1/cognify/code_graph_pipeline.py, cognee/modules/chunking/TextChunker.py, cognee/modules/data/processing/document_types/Document.py, cognee/modules/data/processing/document_types/ImageDocument.py, cognee/modules/data/processing/document_types/PdfDocument.py, cognee/modules/data/processing/document_types/TextDocument.py, cognee/modules/data/processing/document_types/UnstructuredDocument.py, cognee/tasks/chunks/chunk_by_paragraph.py, cognee/tasks/documents/extract_chunks_from_documents.py
Overcome ContextWindowExceededError by checking token count while chunking
=> Overcome ContextWindowExceededError by checking token count while chunking

cognee/api/v1/cognify/code_graph_pipeline.py, cognee/modules/retrieval/code_retriever.py
=> fix: send UUID node ids instead of strings

cognee-mcp/uv.lock
=> fix: fix lock

README.md
=> docs: add demo videos to readme

cognee/shared/logging_utils.py
Add fixes for logger, specifically:
- Add handler when users don't have microseconds
- Resolve issue with multiprocess logging
=> Fix logging [COG-1747]

docker-compose.yml
Until we release a stable and usable frontend commenting it out of docker compose
=> chore: Remove frontend from docker-compose

.github/workflows/test_code_graph_example.yml, cognee-mcp/src/server.py, examples/python/code_graph_example.py, poetry.lock, pyproject.toml
- Redirect all Cognee output to stderr for MCP ( as stdout is used to communicate between MCP Client and server )
- Add test for CODE search type
- Resolve missing optional GUI dependency
=> Fix codify mcp

Dockerfile
Explicit is better than implicit.
https://peps.python.org/pep-0020/#the-zen-of-python
=> feat: follow extras in Docker

.env.template, cognee/base_config.py, cognee/modules/users/methods/create_default_user.py, cognee/modules/users/methods/get_default_user.py
=> feat: Add default user to config

cognee/infrastructure/databases/vector/pgvector/PGVectorAdapter.py
Resolve issues with duplicate chunks for PGVector
=> fix: Resolve duplicate chunk issue for PGVector [COG-895]

cognee-mcp/src/server.py, notebooks/graphrag_vs_rag.ipynb
Resolve failing test for RAG_COMPLETION, add RAG_COMPLETION to MCP
=> fix: Resolve failing test for RAG_COMPLETION, add RAG_COMPLETION to MCP

.github/workflows/test_ollama.yml
=> fix: ollama test embedding endpoint

cognee/shared/logging_utils.py
Resolve issue with missing name if no attribute
=> fix: Resolve issue with missing name if no attribute

cognee/tasks/storage/index_graph_edges.py
Fixes the embedding error for index graph edges
=> fix: Index graph edges embedding error

cognee/infrastructure/databases/vector/embeddings/config.py, cognee/infrastructure/databases/vector/embeddings/get_embedding_engine.py, cognee/tasks/chunks/chunk_by_sentence.py
Resolve issue noticed by [RyabykinIlya](https://github.com/RyabykinIlya) where too many HuggingFace requests have been sent due to the embedding engine not working as a singleton per config
=> Hf tokenizer chunking fix

cognee-mcp/src/server.py
Add CHUNKS search handling and better unknown search type return value
=> fix: return appropriate result type for chunks search in mcp

cognee/exceptions/exceptions.py, cognee/infrastructure/databases/graph/graph_db_interface.py, cognee/infrastructure/databases/vector/exceptions/exceptions.py, cognee/infrastructure/databases/vector/pgvector/PGVectorAdapter.py
Add log handling options for cognee exceptions
=> feat: Add detailed log handling options for Cognee exceptions [COG-1983]

poetry.lock, pyproject.toml, uv.lock
Fix issue with failing versions gh actions
=> Fix versions gh actions [COG-2025]

poetry.lock, pyproject.toml, uv.lock
=> fix: make onnxruntime flexible

cognee/complex_demos/crewai_demo/src/crewai_demo/github_datapoint_creators.py, cognee/complex_demos/crewai_demo/src/crewai_demo/github_datapoints.py, cognee/complex_demos/crewai_demo/src/crewai_demo/github_dev_comments.py, cognee/complex_demos/crewai_demo/src/crewai_demo/github_ingest_datapoints.py
=> feat: Crewai Demo Implementation Datapoints

cognee/complex_demos/crewai_demo/src/crewai_demo/github_dev_comments.py
=> feat: fetch all comments

alembic/versions/1d0bb7fede17_add_pipeline_run_status.py, alembic/versions/482cd6517ce4_add_default_user.py
…exist case
Fixes pipeline run status migration
=> Fix: Fixes pipeline run status migration

cognee/modules/retrieval/utils/brute_force_triplet_search.py
=> Fix: Fixes graph completion search limit

cognee/api/v1/delete/routers/get_delete_router.py
=> fix: hotfix the file uploader in the delete router.

cognee/modules/chunking/models/DocumentChunk.py, cognee/modules/engine/models/EntityType.py, cognee/modules/engine/operations/setup.py, cognee/modules/retrieval/EntityCompletionRetriever.py, cognee/modules/retrieval/chunks_retriever.py, cognee/modules/retrieval/code_retriever.py, cognee/modules/retrieval/completion_retriever.py, cognee/modules/retrieval/cypher_search_retriever.py, cognee/modules/retrieval/graph_completion_context_extension_retriever.py, cognee/modules/retrieval/graph_completion_cot_retriever.py, cognee/modules/retrieval/graph_completion_retriever.py, cognee/modules/retrieval/graph_summary_completion_retriever.py, cognee/modules/retrieval/insights_retriever.py, cognee/modules/retrieval/natural_language_retriever.py, cognee/modules/retrieval/summaries_retriever.py
=> Docstring modules.

pyproject.toml
=> version: v0.1.41

examples/python/relational_database_migration_example.py
Update migration example for upcoming blog on main branch
=> refactor: Add better example information [main branch]

cognee/infrastructure/databases/graph/get_graph_engine.py, cognee/infrastructure/databases/graph/neo4j_driver/adapter.py
adds and invokes Neo4jAdapter initialize for schema setup
=> Fix: adds and invokes Neo4jAdapter initialize for schema setup

cognee/eval_framework/analysis/metrics_calculator.py, cognee/eval_framework/evaluation/deep_eval_adapter.py
- Implemented retries when deepeval's evaluation fails
- Updated metric aggregation to ignore Nones
=> fix: deepeval retry

cognee/modules/retrieval/graph_completion_retriever.py
Adds description to context in graph completion and its subclasses
=> Adds description to context in graph completion and its subclasses

examples/python/agentic_reasoning_procurement_example.py
Adds agentic procurement example
=> Adds agentic procurement example

examples/python/code_graph_example.py
=> refactor: Change include docs to false by default

SECURITY.md
=> docs: Add security.md

cognee/modules/ontology/rdf_xml/OntologyResolver.py
Changes empty ontology logging from warning to info
=> Chore: Changes empty ontology logging from warning to info

CONTRIBUTING.md
=> docs: add dev branch note

cognee-mcp/README.md, cognee-mcp/pyproject.toml
=> chore: mcp readme rewrite

pyproject.toml, uv.lock
=> version: v0.1.43

README.md
=> chore: add sponsor to readme dev

cognee-mcp/README.md
=> fix: update README.md

README.md
=> chore: announce SaaS launch on readme (dev)

cognee-mcp/entrypoint.sh
…isible
Sets cognee mcp server to sse mode 
=> fix: sets cognee mcp server to sse mode

cognee-mcp/pyproject.toml, cognee-mcp/uv.lock
=> chore: upgrade cognee package

cognee/modules/pipelines/operations/pipeline.py
Resolve issue with write permission for different users
=> Fix write permission different user

cognee-mcp/Dockerfile
Removes env copy from mcp docker file
=> chore: Removes .env copy from mcp dockerfile

cognee/tasks/chunks/chunk_by_paragraph.py
…cut type
Fixes pdf cut type None bug by introducting default cut type
=> Fix: Fixes pdf cut type None bug by introducting default cut type

.env.template, cognee/api/v1/add/routers/get_add_router.py, cognee/api/v1/delete/delete.py, cognee/api/v1/delete/routers/get_delete_router.py, cognee/infrastructure/engine/models/DataPoint.py, cognee/tasks/ingestion/save_data_item_to_storage.py
Modify endpoints to allow better security for different infrastructure needs and setups
=> Secure api v2

.github/workflows/e2e_tests.yml, cognee/api/v1/cognify/cognify.py, cognee/api/v1/delete/delete.py, cognee/modules/search/methods/search.py, cognee/tasks/ingestion/ingest_data.py, cognee/tests/test_permissions.py
Add tests for permissions for Cognee
=> feat: Add test for permissions, change Cognee search return value

README.md, cognee-mcp/entrypoint.sh
=> Merge main vol3

cognee/api/v1/add/routers/get_add_router.py, cognee/api/v1/cognify/routers/get_cognify_router.py, cognee/api/v1/datasets/routers/get_datasets_router.py, cognee/api/v1/permissions/routers/get_permissions_router.py, cognee/api/v1/search/routers/get_search_router.py, cognee/api/v1/settings/routers/get_settings_router.py, cognee/api/v1/users/routers/get_visualize_router.py
=> fix: Add docstrings to routers

cognee/infrastructure/files/utils/get_file_metadata.py, cognee/modules/data/models/Data.py, cognee/tasks/ingestion/ingest_data.py
=> feat: Data size info tracking

cognee/infrastructure/databases/graph/kuzu/adapter.py
Change Kuzu default buffer size
=> refactor: Add Kuzu buffer change

cognee/api/v1/datasets/routers/get_datasets_router.py
=> fix: Resolve issue with dataset status endpoint

pyproject.toml, uv.lock
=> version: v0.2.1.dev5

pyproject.toml, uv.lock
=> version: v0.2.1.dev6

cognee/api/client.py, poetry.lock, pyproject.toml, uv.lock
Fix: Fixes psycopg2 error when pg_config is not installed
=> Fix: Fixes psycopg2 error when pg_config is not installed

cognee/api/client.py, cognee/api/v1/add/add.py, cognee/api/v1/add/routers/get_add_router.py, cognee/api/v1/cognify/routers/get_cognify_router.py, cognee/api/v1/search/routers/get_search_router.py, cognee/modules/ingestion/classify.py
Simplify Cognee endpoints so default dataset ID will be None
=> refactor: simplify endpoint default values

cognee/api/v1/add/routers/get_add_router.py, cognee/api/v1/cognify/routers/get_cognify_router.py, cognee/api/v1/datasets/routers/get_datasets_router.py, cognee/api/v1/delete/routers/get_delete_router.py, cognee/api/v1/permissions/routers/get_permissions_router.py, cognee/api/v1/search/routers/get_search_router.py, cognee/api/v1/users/routers/get_visualize_router.py
=> fix: add api tracking events

cognee/modules/graph/cognee_graph/CogneeGraph.py, cognee/modules/retrieval/utils/brute_force_triplet_search.py
Optimizes query embedding by reducing the number of query embedding calls and avoids multiple edge collection searches when they are available.
=> Feature: optimizes query embedding and edge collection search

cognee/infrastructure/databases/relational/sqlalchemy/SqlAlchemyAdapter.py
Sets sqlalchemy pool_size and max overflow to a hard limit instead of default values
=> chore: Sets sqlalchemy pool_size and max overflow to a hard limit instead of default values

poetry.lock, uv.lock
=> chore: Update lock files

pyproject.toml, uv.lock
=> version: v0.2.1

CONTRIBUTING.md
=> fix: Update CONTRIBUTING.md

cognee-mcp/Dockerfile, cognee-mcp/entrypoint.sh, cognee-mcp/pyproject.toml, cognee-mcp/src/server.py, cognee-mcp/uv.lock
Resolve issues with Cognee MCP docker use
=> Cognee mcp docker fix

cognee/temporal_poc/datapoints/datapoints.py, cognee/temporal_poc/event_extraction.py, cognee/temporal_poc/event_knowledge_graph.py, cognee/temporal_poc/models/models.py, cognee/temporal_poc/temporal_cognify.py, cognee/temporal_poc/temporal_example.py, cognee/temporal_poc/temporal_retriever.py
=> feature: extract entities from events

alembic/versions/1daae0df1866_incremental_loading.py, cognee/modules/pipelines/operations/run_tasks.py
Add relational db migration for incremental loading, change incremental loading to work document per document instead of async together
=> Incremental loading migration

pyproject.toml
=> feat: Change cognee version

pyproject.toml
=> chore: Update Cognee version

cognee/api/v1/cognify/cognify.py, cognee/modules/pipelines/layers/pipeline_execution_mode.py
feature: adds pipeline execution layer to cognify
=> feature: adds pipeline execution layer to cognify

cognee/api/v1/cognify/cognify.py, cognee/tests/test_search_db.py
fix: fixes search test behaviour and adds comments to new pipeline executor logic
=> fix: fixes search test behaviour and adds comments to new pipeline executor logic

cognee-mcp/pyproject.toml
=> chore: Update mcp version

cognee/modules/data/deletion/prune_system.py
=> fix: Make metadata prune true by default

.github/workflows/test_openrouter.yml, .github/workflows/test_suites.yml
=> fix: Add openrouter test

cognee-mcp/pyproject.toml, cognee-mcp/src/server.py, cognee-mcp/uv.lock
=> fix: Return coding rules to MCP

cognee/infrastructure/llm/structured_output_framework/litellm_instructor/llm/openai/adapter.py, poetry.lock, pyproject.toml, uv.lock
=> feat: Add low reasoning for gpt5 model

cognee-starter-kit/src/pipelines/low_level.py, cognee/modules/data/methods/load_or_create_datasets.py, examples/low_level/pipeline.py
=> fix: update low level examples

cognee/modules/retrieval/temporal_retriever.py
=> fix: temporal retriever return values

cognee-frontend/src/ui/elements/Notebook/Notebook.tsx, cognee/modules/search/methods/search.py, cognee/modules/search/utils/prepare_search_result.py, cognee/modules/search/utils/transform_context_to_graph.py, cognee/modules/search/utils/transform_insights_to_graph.py
=> fix: combined context search

.env.template, cognee/modules/search/methods/get_search_type_tools.py
Make Cypher search optional
Security upgrade
Made cypher search optional for security reasons
Tried running cypher queries with feature turned on and off
=> refactor: make cypher query optional

cognee/modules/pipelines/models/PipelineRunInfo.py
Enable Data object serialization when returning PipelineRunInfo type objects in backend
- 
- 
- 
=> fix: Resolve issue with Data object serialization

cognee-frontend/src/app/account/Account.tsx, cognee-frontend/src/app/dashboard/AddDataToCognee.tsx, cognee-frontend/src/app/dashboard/Dashboard.tsx, cognee-frontend/src/app/dashboard/InstanceDatasetsAccordion.tsx, cognee-frontend/src/app/dashboard/NotebooksAccordion.tsx, cognee-frontend/src/app/globals.css, cognee-frontend/src/app/plan/Plan.tsx, cognee-frontend/src/ui/Layout/Header.tsx, cognee-frontend/src/ui/elements/GhostButton.tsx, cognee-frontend/src/ui/elements/Modal/useModal.ts, cognee-frontend/src/ui/elements/Notebook/Notebook.tsx, cognee-frontend/src/ui/elements/Notebook/NotebookCellHeader.tsx, cognee-frontend/src/ui/elements/index.ts, cognee-frontend/src/utils/fetch.ts, cognee-frontend/src/utils/handleServerErrors.ts, cognee/api/v1/cloud/routers/get_checks_router.py
=> fix: UI fixes

poetry.lock, pyproject.toml, uv.lock
=> fix: limit onnxruntime version

cognee-frontend/src/ui/Layout/Header.tsx, cognee-frontend/src/ui/elements/StatusDot.tsx, cognee-frontend/src/ui/elements/index.ts, cognee-frontend/src/utils/fetch.ts, cognee-mcp/entrypoint.sh, cognee-mcp/pyproject.toml, cognee-mcp/src/server.py, cognee/api/v1/ui/__init__.py, cognee/api/v1/ui/ui.py, cognee/cli/_cognee.py, examples/start_ui_example.py
=> feat: start mcp in ui cli command

cognee/infrastructure/llm/structured_output_framework/litellm_instructor/llm/openai/adapter.py
Resolve issues with gpt 5 models for structured outputs by forcing JSON mode in instructor
=> fix: Resolve issues with GPT5 models

cognee/tests/cli_tests/cli_unit_tests/test_cli_edge_cases.py
Github Actions job:
https://github.com/topoteretes/cognee/actions/runs/18199627173/job/51815009426?pr=1493
=> Fix test_cli_edge_cases, test_delete_all_with_user_id unit test

cognee/api/v1/add/add.py, cognee/modules/pipelines/layers/resolve_authorized_user_dataset.py, cognee/modules/pipelines/layers/resolve_authorized_user_datasets.py, cognee/modules/search/methods/search.py
Unified dataset resolution mechanisms across cognee
=> refactor: Unify dataset resolution

cognee/infrastructure/databases/vector/pgvector/PGVectorAdapter.py
Reduce time PGVector is using async lock, by checking if collection exists before taking async lock
=> refactor: Don't use async lock if not needed
